import pandas as pd
cars=pd.read_csv('cars.csv')
print(cars.iloc[0:5,0:12:2])
print(cars.loc[cars['Model']=='Mazda RX4'])
print('for Camaro Z28:')
print(cars.loc[cars['Model']=='Camaro Z28',['cyl']])
print('for Mazda RX4 Wag:')
print(cars.loc[cars['Model']=='Mazda RX4 Wag',['cyl']])
print(cars.loc[cars['Model']=='Mazda RX4 Wag',['gear']])
print('for Ford Pantera L:')
print(cars.loc[cars['Model']=='Ford Pantera L',['cyl']])
print(cars.loc[cars['Model']=='Ford Pantera L',['gear']])
print('for Honda Civic:')
print(cars.loc[cars['Model']=='Honda Civic',['cyl']])
print(cars.loc[cars['Model']=='Honda Civic',['gear']])